---
title: "MentalHealthEDA"
author: "Hugo Baca"
date: "2023-07-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
#read our cleaned up data into the env
data_analytic<- readRDS("data/interim/analytic2023_c1.rds")
```

```{r}
#we want to plot poor mental health days and PHS
#race break down DNE
#PMHD(v042_rawvalue):Average number of mentally unhealthy days reported in past 30 days (age-adjusted).
ggplot(data_analytic, aes(y = v005_rawvalue, x = v042_rawvalue))+
  geom_point(color="green", alpha =0.5)+
  geom_smooth()+
  xlab(paste("Average number of mentally unhealthy days reported in past 30 days (age-adjusted).")) +
  ylab("Preventable Hospital Stays")+
  theme(panel.background = element_rect(fill = "black"),
           plot.background = element_rect(fill = "black"),
           panel.grid.major = element_line(color = "white", size = 0.1),
           panel.grid.minor = element_line(color = "white", size = 0.05),
           text = element_text(color = "white"))
```

```{r}
#phs vs frequent mental distress
#race break down DNE
#FMD(v145):Percentage of adults reporting 14 or more days of poor mental health per month (age-adjusted).
ggplot(data_analytic, aes(y = v005_rawvalue, x = v145_rawvalue))+
  geom_point(color="green",alpha =0.5)+
  geom_smooth() +
  xlab(paste("Ratio of household income at the 80th percentile to income at the 20th percentile.")) +
  ylab("Preventable Hospital Stays") +
  theme(panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = "white", size = 0.1),
        panel.grid.minor = element_line(color = "white", size = 0.05),
        text = element_text(color = "white"))

```


```{r}
#phs vs poor or fair health 
#race break down DNE
#PFH(v002):Percentage of adults reporting fair or poor health (age-adjusted).
ggplot(data_analytic, aes(y = v005_rawvalue, x = v002_rawvalue))+
  geom_point(color="green", alpha =0.5)+
  geom_smooth()+
  xlab(paste("Percentage of adults reporting fair or poor health (age-adjusted)")) +
  ylab("Preventable Hospital Stays") +
  theme(panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = "white", size = 0.1),
        panel.grid.minor = element_line(color = "white", size = 0.05),
        text = element_text(color = "white"))
```

```{r}
#phs vs Drug overdase Raw
#v138 Drug overdose: Number of drug poisoning deaths per 100,000 population.
ggplot(data_analytic, aes(y = v005_rawvalue, x = v138_rawvalue))+
  geom_point(color="green", alpha =0.5)+
  geom_smooth()+
  xlab(paste("Number of drug poisoning deaths per 100,000 population.")) +
  ylab("Preventable Hospital Stays") +
  theme(panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = "white", size = 0.1),
        panel.grid.minor = element_line(color = "white", size = 0.05),
        text = element_text(color = "white"))
```

```{r}
#phs vs Drug overdase by race
v138_xaxis_vars <- c("v138_race_hispanic", "v138_race_white", "v138_race_asian", "v138_race_aian", "v138_race_black")
for(var in v138_xaxis_vars){
  va138byracegraph <- ggplot(data_analytic, aes_string(y = "v005_rawvalue", x = var))+
    geom_point(color="green", alpha =0.5)+
    geom_smooth()+
    xlab(paste(var, ":Number of drug poisoning deaths per 100,000 population.")) +
    ylab("Preventable Hospital Stays")+
    theme(panel.background = element_rect(fill = "black"),
          plot.background = element_rect(fill = "black"),
          panel.grid.major = element_line(color = "white", size = 0.1),
          panel.grid.minor = element_line(color = "white", size = 0.05),
          text = element_text(color = "white")) 
    print(va138byracegraph)
}
```







