---
title: "TransitVarsvsPHS"
author: "Hugo Baca"
date: "2023-07-01"
output: html_document
---
```{r}
library(tidyverse)
library(ggplot2)
data_analytic<- readRDS("../../../../test/data/interim/analytic2023_c1.rds")
```
Motor vehicle deaths raw(v039):Number of motor vehicle crash deaths per 100,000 population.
Drive along to work (v067):Percentage of the workforce that drives alone to work.
Long Commute Alone (v137): Among workers who commute in their car alone, the percentage that commute more than 30 minutes.
No break down by race for 067 & 137

```{r}
ggplot(data_analytic, aes(y = v005_rawvalue, x = v039_rawvalue))+
  geom_point(color="green", alpha =0.5)+
  geom_smooth()+
  xlab(paste("Number of motor vehicle crash deaths per 100,000 population.")) +
  ylab("Preventable Hospital Stays")+
  theme(panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = "white", size = 0.1),
        panel.grid.minor = element_line(color = "white", size = 0.05),
        text = element_text(color = "white"))

ggplot(data_analytic, aes(y = v005_rawvalue, x = v067_rawvalue))+
  geom_point(color="green", alpha =0.5)+
  geom_smooth()+
  xlab(paste("Percentage of the workforce that drives alone to work.")) +
  ylab("Preventable Hospital Stays")+
  theme(panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = "white", size = 0.1),
        panel.grid.minor = element_line(color = "white", size = 0.05),
        text = element_text(color = "white"))

ggplot(data_analytic, aes(y = v005_rawvalue, x = v137_rawvalue))+
  geom_point(color="green", alpha =0.5)+
  geom_smooth()+
  xlab(paste("Among workers who commute in their car alone, the percentage that commute more than 30 minutes.")) +
  ylab("Preventable Hospital Stays")+
  theme(panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = "white", size = 0.1),
        panel.grid.minor = element_line(color = "white", size = 0.05),
        text = element_text(color = "white"))

```


```{r}
v039_xaxis_vars <- c("v039_race_hispanic", "v039_race_white", "v039_race_asian", "v039_race_aian", "v039_race_black")
for(var in v039_xaxis_vars){
  va148byracegraph <- ggplot(data_analytic, aes_string(y = "v005_rawvalue", x = var))+
    geom_point(color="green", alpha =0.5)+
    geom_smooth()+
    xlab(paste(var, ":Number of motor vehicle crash deaths per 100,000 population.
.")) +
    ylab("Preventable Hospital Stays")+
    theme(panel.background = element_rect(fill = "black"),
          plot.background = element_rect(fill = "black"),
          panel.grid.major = element_line(color = "white", size = 0.1),
          panel.grid.minor = element_line(color = "white", size = 0.05),
          text = element_text(color = "white")) 
    print(va148byracegraph)
}
```

```{r}
v067_xaxis_vars <- c("v067_race_hispanic", "v067_race_white", "v067_race_asian", "v067_race_aian", "v067_race_black")
#Race: Hispanic
for(var in v067_xaxis_vars){
  va148byracegraph <- ggplot(data_analytic, aes_string(y = "v005_rawvalue", x = var))+
    geom_point(color="green", alpha =0.5)+
    geom_smooth()+
    xlab(paste(var, ":Percentage of the workforce that drives alone to work.")) +
    ylab("Preventable Hospital Stays")+
    theme(panel.background = element_rect(fill = "black"),
          plot.background = element_rect(fill = "black"),
          panel.grid.major = element_line(color = "white", size = 0.1),
          panel.grid.minor = element_line(color = "white", size = 0.05),
          text = element_text(color = "white")) 
    print(va148byracegraph)
}
```

