---
title: "Cleaning"
author: "Hugo Baca"
date: "2023-06-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#analytics
```{r}
library(tidyverse)
data_analytic <- read_csv("../../../data/raw/analytic_data2023_0.csv",skip=1)

# Check if any of the column contains only the NA

# Drop such columns

isColAllNA = data_analytic %>% lapply(., function(x) all(is.na(x))) %>% unlist
data_analytic %>% select(-c(1))
which(isColAllNA)
foo =which(isColAllNA)

data_analytic %>% select(-all_of(foo))

data_analytic$state %>% table(useNA="always")
data_analytic$statecode %>% table(useNA="always")
# Check if any of the column contains only the single value.

# Document and drop the column
single_value_cols <- apply(data_analytic, 2, function(x) length(unique(x)) == 1)
print(single_value_cols)

single_values =which(single_value_cols)
data_analytic %>% select(-single_values)

data_analytic_interim <-  data_analytic %>% select(-single_values)

```

#we are now analyzing trends
```{r}
#access trends data
data_trends <- read_csv("../../../data/raw/chr_trends_csv_2023.csv")
head(data_trends)

#find col where all values = NA
isColAllNA_trend = data_trends %>% lapply(., function(x) all(is.na(x))) %>% unlist
print(isColAllNA_trend)

#get 
foo_trend = which(isColAllNA_trend)
#remove col where all values = NA
data_trends%>% select(-all_of(foo_trend))

#finally, assign data to a var
data_trends_interim <- data_trends

#find cols containing only one the single value
single_value_cols_trend <- apply(data_trends, 2, function(x) length(unique(x)) == 1)

#get 
single_value_trend <- which(single_value_cols_trend)

print(single_value_cols_trend)

print(single_value_trend)

#remove cols that contain only one single value
data_trends_interim <- data_trends %>% select(-single_value_trend)

print(data_trends_interim)
#we have two data frames of cleaned up data 
```
#let's do exploratory analsis
#lets plot inequilty in the state of New York within queens county
#we will use the data in analytics
```{r}
#grabeed all preventable stays within Queens County of New York
data_trends_interim %>% filter(state =='NY' & county == "Queens County" & measurename == "Preventable hospital stays")


data_analytic_interim %>% filter(state =='NY' & county == "Queens County" & v044_rawvalue > 0)
#v005_rawvalue - prevetbale stays 
#v044_rawvalue - income inequality
data_analytic_interiminterim %>%
#  filter(  v044_rawvalue > 0 & v005_rawvalue >0) %>%
  ggplot(aes(x = v005_rawvalue, y = v044_rawvalue)) +
  geom_point(color=ifelse(data_analytic_interim$state=="NY", "red", "blue"), alpha=0.3)


#grab all inequality 

```

# California income inequality vs highschool completion
```{r}
data_analytic_interim %>%
#  filter(  v044_rawvalue > 0 & v005_rawvalue >0) %>%
  ggplot(aes(x = v005_rawvalue, y = v168_rawvalue)) +
  geom_point(color=ifelse(data_analytic_interim$state=="CA", "red", "blue"), alpha=0.3)


```

