---
title: "andrea hospital stays"
author: "Andrea"
date: "2023-06-16"
output: html_document
---

```{r}
data_analytics <- read_csv('data/raw/analytic_data2023_0.csv', skip = 1)
```

```{r}
# Script to create variable description
#
# The original data has two rows:
# 1. the long description and 2. the encoded name
# Output is 1 row dataframe of desc (row1) with column names (row2)
library(tidyverse)
desc = colnames(read_csv("data/raw/analytic_data2023_0.csv", n_max=1))
enc = colnames(read_csv("data/raw/analytic_data2023_0.csv", skip=1, n_max=1))

descriptions = data.frame(t(desc))
colnames(descriptions) = enc
row.names(descriptions) = "description"
saveRDS(descriptions, "data/processed/colDesc_analysis2023.rds")

# Use case
descriptions %>% select(starts_with("v005_rawvalue"))
#                                   v005_rawvalue
#description Preventable Hospital Stays raw value
```
```{r}
data_analytics %>% ggplot( aes(x=v023_rawvalue, y=v005_rawvalue))+
  geom_point(color = ifelse(data_analytics$state =="CA", 'black', 'pink'), alpha=0.3)
  
```

```
#Above is xaxis preventable hospital stays and yaxis unemployment raw rate
```

```{r}
data_analytics %>% ggplot(aes(x=v168_rawvalue, y=v005_rawvalue))+
  geom_point(color = ifelse(data_analytics$state =="CA", 'red', 'blue'), alpha=0.3) +
  labs(x = "High School Completion", y= "Preventable Hospital Stays")
```
#Above x= high school completion and y= Preventable hospital stays

















```{r}

```




