---
title: "Community and Support"
output: html_document
date: "2023-07-22"
---
#Community and Support

```{r}
library(tidyverse)
library(ggplot2)
```

#gives plott w all races
```{r}
#Injury deaths Raw(v135):Number of deaths due to injury per 100,000 population.
ggplot(data_analytic, aes(y = v005_rawvalue, x = v135_rawvalue))+
  geom_point(color="green", alpha =0.5)+
  geom_smooth()+
  xlab(paste("Number of deaths due to injury per 100,000 population")) +
  ylab("Preventable Hospital Stays")+
  theme(panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = "white", size = 0.1),
        panel.grid.minor = element_line(color = "white", size = 0.05),
        text = element_text(color = "white"))
```

#check if it is the same above

```{r}
v135_xaxis_vars <- c("v135_race_hispanic", "v135_race_white", "v135_race_asian", "v135_race_aian", "v135_race_black")
v005_race_yaxis <- c("v005_race_hispanic","v005_race_white","v005_race_asian","v005_race_aian","v005_race_black")

# assuming the length of both vectors is the same
for(i in 1:length(v135_xaxis_vars)){
  var_x <- v135_xaxis_vars[i]
  var_y <- v005_race_yaxis[i]
  
  va135byracegraph <-ggplot(data_analytic, aes_string(y = var_y, x = var_x))+
    geom_point(color="green", alpha =0.5)+
    geom_smooth()+
    xlab(paste(var_x, ":Number of deaths due to injury per 100,000 population.")) +
    ylab(paste(var_y, ":Preventable Hospital Stays"))+
    theme(panel.background = element_rect(fill = "black"),
          plot.background = element_rect(fill = "black"),
          panel.grid.major = element_line(color = "white", size = 0.1),
          panel.grid.minor = element_line(color = "white", size = 0.05),
          text = element_text(color = "white")) 
  print(va135byracegraph)
}
```

#Suicides
```{r}
v161_xaxis_vars <- c("v161_race_hispanic", "v161_race_white", "v161_race_asian", "v161_race_aian", "v161_race_black")
#Race: Hispanic
v005_race_yaxis <- c("v005_race_hispanic","v005_race_white","v005_race_asian","v005_race_aian","v005_race_black")

# assuming the length of both vectors is the same
for(i in 1:length(v135_xaxis_vars)){
  var_x <- v135_xaxis_vars[i]
  var_y <- v005_race_yaxis[i]
  
  va135byracegraph <-ggplot(data_analytic, aes_string(y = paste0("log(",var_y,")"), x = paste0("log(",var_x,")")))+
    geom_point(color="green", alpha =0.5)+
    geom_smooth()+
    xlab(paste(var_x, ":Number of deaths due to suicide per 100,000 population (age-adjusted)")) +
    ylab(paste(var_y, ":Preventable Hospital Stays"))+
    theme(panel.background = element_rect(fill = "black"),
          plot.background = element_rect(fill = "black"),
          panel.grid.major = element_line(color = "white", size = 0.1),
          panel.grid.minor = element_line(color = "white", size = 0.05),
          text = element_text(color = "white")) 
  print(va135byracegraph)
}
```

#Firearms

```{r}
#fire arm deaths raw(v148):Number of deaths due to firearms per 100,000 population.
ggplot(data_analytic, aes(y = v005_rawvalue, x = v148_rawvalue))+
  geom_point(color="green", alpha =0.5)+
  geom_smooth()+
  xlab(paste("Number of deaths due to firearms per 100,000 population.")) +
  ylab("Preventable Hospital Stays")+
  theme(panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = "white", size = 0.1),
        panel.grid.minor = element_line(color = "white", size = 0.05),
        text = element_text(color = "white"))
```


#firearms by race

```{r}
v148_xaxis_vars <- c("v148_race_hispanic", "v148_race_white", "v148_race_asian", "v148_race_aian", "v148_race_black")
#Race: Hispanic
v005_race_yaxis <- c("v005_race_hispanic","v005_race_white","v005_race_asian","v005_race_aian","v005_race_black")

# assuming the length of both vectors is the same
for(i in 1:length(v135_xaxis_vars)){
  var_x <- v135_xaxis_vars[i]
  var_y <- v005_race_yaxis[i]
  
  va135byracegraph <-ggplot(data_analytic, aes_string(y = var_y, x = var_x))+
    geom_point(color="green", alpha =0.5)+
    geom_smooth()+
    xlab(paste(var_x, ":Number of deaths due to injury per 100,000 population.")) +
    ylab(paste(var_y, ":Preventable Hospital Stays"))+
    theme(panel.background = element_rect(fill = "black"),
          plot.background = element_rect(fill = "black"),
          panel.grid.major = element_line(color = "white", size = 0.1),
          panel.grid.minor = element_line(color = "white", size = 0.05),
          text = element_text(color = "white")) 
  print(va135byracegraph)
}
```



