---
title: "Megan Preventable Hospitals"
output: html_document
date: "2023-06-09"
---



```{r}
library(readr)
library(dplyr)
library(ggplot2)

trends <- read_csv("../data/raw/chr_trends_csv_2023.csv")
data = read_csv("../data/raw/analytic_data2023_0.csv", skip = 1)
View(trends)


#create a line graph that looks at different states and unemployment rates
unemployment  = trends

#1. create new var that looks at states and unemployment rates 

#2. aggregate all the counties together within a year and each point = aggregation of all counties 

test = unemployment %>% filter(measurename == "Unemployment rate") %>% 
  group_by(state,yearspan) %>% 
  summarize(mean_raw = mean(rawvalue))

ggplot(test, aes(x = yearspan, y = mean_raw, color = state, group = state)) +
   geom_line()+
   geom_point()

```

#MAPPING ALL THE REGIONS 
```{r}
#NORTHEAST
northeast = unemployment %>%  
filter(measurename == "Unemployment rate", state %in% c("CT", "ME", "MA", "NH", "RI", "VT", "NJ", 'NY', 'PA')) %>% 
group_by(state, yearspan) %>% 
summarize(mean_raw = mean(rawvalue)) %>% 
ggplot(aes(x = yearspan, y = mean_raw, color = state, group = state)) + 
geom_line() +
geom_point()
  
northeast


#MIDWEST
midwest = unemployment %>%  
filter(measurename == "Unemployment rate", state %in% c("IL", "IN", "MI", "OH", "WI", "IA", "KS", 'MN', 'MO', 'NE','ND', 'SD')) %>% 
group_by(state, yearspan) %>% 
summarize(mean_raw = mean(rawvalue)) %>% 
ggplot(aes(x = yearspan, y = mean_raw, color = state, group = state)) + 
geom_line() +
geom_point()

midwest

#SOUTH 
south = unemployment %>%  
filter(measurename == "Unemployment rate", state %in% c("DE", "FL", "GA", "MD", "NC", "SC", "VA", 'WV', 'MO', 'NE','ND', 'SD')) %>% 
group_by(state, yearspan) %>% 
summarize(mean_raw = mean(rawvalue)) %>% 
ggplot(aes(x = yearspan, y = mean_raw, color = state, group = state)) + 
geom_line() +
geom_point()

south


#WEST
west = unemployment %>%  
filter(measurename == "Unemployment rate", state %in% c("AZ", "CO", "ID", "MT", "NV", "NM", "UT", 'WY')) %>% 
group_by(state, yearspan) %>% 
summarize(mean_raw = mean(rawvalue)) %>% 
ggplot(aes(x = yearspan, y = mean_raw, color = state, group = state)) + 
geom_line() +
geom_point()

#MAKE SURE ALL THE SCALES ARE THE SAME WHEN COMPARING ACROSS DIFF GRAPHS 

```






```{r}
#testing AK 

test_state = 
  unemployment %>% filter(measurename == "Unemployment rate", state %in% c("CO", "NY")) %>% 
  group_by(state, yearspan) %>% 
  summarize(mean_raw = mean(rawvalue)) 

ggplot(test_state, aes(x = yearspan, y = mean_raw, color = state, group = state)) +
   geom_line()+
   geom_point()

test_state
#got rid of the color = state arguement 

#test states
AK =  unemployment %>% filter(measurename == "Unemployment rate", state == "AK") %>% 
  group_by(state, yearspan) %>% 
  summarize(mean_raw = mean(rawvalue)) 

ggplot(AK, aes(x = yearspan, y = mean_raw, color = state, group =1)) +
   geom_line()+
   geom_point()


CO =  unemployment %>% filter(measurename == "Unemployment rate", state == "CO") %>% 
  group_by(state, yearspan) %>% 
  summarize(mean_raw = mean(rawvalue)) 

ggplot(CO, aes(x = yearspan, y = mean_raw, color = state, group =1)) +
   geom_line()+
   geom_point()


NY =  unemployment %>% filter(measurename == "Unemployment rate", state == "NY") %>% 
  group_by(state, yearspan) %>% 
  summarize(mean_raw = mean(rawvalue)) 

ggplot(NY, aes(x = yearspan, y = mean_raw, color = state, group =1)) +
   geom_line()+
   geom_point()
```
   
   
   

```{r}
#HEAT MAP OVERLAY 
install.packages("usmap")
library(usmap)
library(tidyverse)
library(ggplot2)

#SCATTERPLOT

#had to skip first line in order to get the headers (no longer need to use backticks to reference columns)

#all 50 for 3 variables
data_all = data %>%  select(4,5,153:162, 193:197, 183:187, 218:222)


testval= (ggplot(data_all,aes(x = v023_rawvalue, y = v005_race_aian  )) + geom_point(alpha = 0.2, color = "orange") + ggtitle("unemployment vs preventable stays for american indian and alaskan natives (aian) ") +geom_smooth() + xlim(0, 0.25) + ylim(0, 30000))

#finding obs points that are in the 30K +
find30k = data_all  %>% 
  select(state, county, v023_rawvalue, v005_race_aian) %>% 
  filter(v005_race_aian > 30000) %>% 
  arrange(-v005_race_aian)
  

View(find30k)
# sevier county, AR only has 4% of population that is AIAN in 2019
#marion county, IN 


#all 50 for asian
ggplot(data_all,aes(x = v023_rawvalue, y = v005_race_asian )) + geom_point(alpha = 0.2, color = "orange") + ggtitle("unemployment vs preventable stays for asians") +geom_smooth() + xlim(0, 0.15) + ylim(0, 30000)



#all 50 for black
ggplot(data_all,aes(x = v023_rawvalue, y = v005_race_black )) + geom_point(alpha = 0.8, color = "blue" )+ ggtitle("unemployment vs preventable stays for blacks")+geom_smooth() + xlim(0, 0.20) + ylim(0, 30000)



#all 50 for hispanic
ggplot(data_all,aes(x = v023_rawvalue, y = v005_race_hispanic )) + geom_point(alpha = 0.8, color = "pink" )+ ggtitle("unemployment vs preventable stays for hispanics")+geom_smooth() + xlim(0, 0.20) + ylim(0, 30000)



#all 50 for white
ggplot(data_all,aes(x = v023_rawvalue, y = v005_race_white )) + geom_point(alpha = 0.2, color = "green" ) +  ggtitle("unemployment vs preventable stays for whites")+geom_smooth() + xlim(0, 0.20) + ylim(0, 30000)


View(data_all)

```

```{r}
# created with all melted data



p <- ggplot(data_long, aes(x = v023_rawvalue, y = value, color = race)) +
  geom_point(alpha = 0.8) +
  labs(x = descriptions[["v023_rawvalue"]], y = "Preventable Hospital Stays") +
  scale_color_discrete(labels = c("Asian", "AIAN", "Black", "Hispanic", "White")) +
  theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    axis.title = element_text(color = "white"),
    axis.text = element_text(color = "white"),
    legend.background = element_rect(fill = "black"),
    legend.text = element_text(color = "white")
  )
```




```{r}
# reshape for unemployment variables 
library(reshape2)
library(reshape2)
library(dplyr)
data_unemployment = data[ , c("state", "county","v024_race_aian","v024_race_asian","v024_race_black","v024_race_hispanic", "v024_race_white")]  #actually v024 is the childcare

#melted data for unemployment ACTUALLY CHILDCARE
ndimdf_unemploy = melt(data_unemployment, id = c("state", "county"),variable.name='race') #this melts the county and state instead of the others
```



```{r}
#chloropleth for unemployment

library(maps)
library(usdata)
state_borders <- map_data("state") %>% 
mutate(state = state2abbr(region)) %>% 
select(-subregion)
head(state_borders)

#gives an avg and filters ou territories, groups by state from melted data
state_unemployment = ndimdf %>%
filter(!is.na(value), !state  %in% "US")  %>% 
group_by(state) %>% 
summarize(avg_unemployment_rate = mean(value)) %>% 
mutate(State = abbr2state(state)) #takes the abbreviations in state and spells it out in a new column called "State)
  
  
state_unemployment_plot <- state_borders %>%
left_join(state_unemployment,
by = join_by(state == state ))#state_borders) #joins on common key in df1 and df2 

state_unemployment_plot %>%
ggplot() +
geom_polygon(aes(x = long, y = lat,
group = group ,
fill = avg_unemployment_rate),
color = "black") +
scale_fill_gradient(
low = "white",
high = "navy") +
theme_void() +
coord_map("polyconic") +
labs(fill = "Avg Unemployment Rate") +
theme(legend.position = "bottom")
```



```{r}
# Script to create variable description
#
# The original data has two rows:
# 1. the long description and 2. the encoded name
# Output is 1 row dataframe of desc (row1) with column names (row2)

library(tidyverse)
desc = colnames(read_csv("../data/raw/analytic_data2023_0.csv", n_max=1))


enc = colnames(read_csv("../data/raw/analytic_data2023_0.csv", skip=1, n_max=1))

descriptions = data.frame(t(desc))
colnames(descriptions) = enc
row.names(descriptions) = "description"
saveRDS(descriptions, "data/processed/colDesc_analysis2023.rds")

# Use case
descriptions %>% select(starts_with("v023_rawvalue"))
```



```{r}
# scatterplot with melted data

library(tidyverse)
library(reshape2)

data_long <- data %>% 
  pivot_longer(cols = starts_with('v005_race'), names_to = "race", values_to = "value") %>% 
  filter(value < 15000)


p <- ggplot(data_long, aes(x = v023_rawvalue, y = value, color = race)) +
  geom_point(alpha = 0.8) +
  labs(x = descriptions[["v023_rawvalue"]], y = "Preventable Hospital Stays") +
  scale_color_discrete(labels = c("AIAN", "Asian", "Black", "Hispanic", "White")) +
  theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    axis.title = element_text(color = "white"),
    axis.text = element_text(color = "white"),
    legend.background = element_rect(fill = "black"),
    legend.text = element_text(color = "white")
  ) +
  geom_smooth()

  print(p)
```
#look at the obs that are above 15k in preventable hospitals and find patterns


```{r}
data_long <- data %>% 
  pivot_longer(cols = starts_with('v005_race'), names_to = "race", values_to = "value")


data_15k <- data %>% 
  pivot_longer(cols = starts_with('v005_race'), names_to = "race", values_to = "value") %>% 
  filter(value > 15000)

data_geo15k <- data %>% 
  pivot_longer(cols = starts_with('v005_race'), names_to = "race", values_to = "value") %>% 
  filter(value > 15000) %>% 
  select(state) %>% 
  table()#selects var you want and then pipes into it to create a table/count



```


```{r}
#creating chloropleth of obs that are above 15k in preventable hospital stays 

library(reshape2)
#melt the data15k values
preventable_race_list <- c("v005_race_aian", "v005_race_asian", "v005_race_black", "v005_race_hispanic", "v005_race_white")

#create new df that has preventable for all races w valuese more than 30000
data_preventable = data %>% 
  select(state, county, all_of(preventable_race_list)) 

ndimdf_preventable1 = melt(data_preventable, id = c("state", "county"),variable.name='race')



ndimdf_preventable15k = ndimdf_preventable1 %>% 
  filter(value  > 15000)
  
 
#have to use melted data to create chloropleth data
greater15k = ndimdf_preventable15k %>% 
  filter(!is.na(value), !state  %in% "US") %>% 
  group_by(state) %>% 
  summarize(phs_rate_15k = mean(value))

state_prevent_plot15k <- state_borders %>%
left_join(greater15k,
by = join_by(state == state ))

state_prevent_plot15k %>%
ggplot() +
geom_polygon(aes(x = long, y = lat,
group = group ,
fill = phs_rate_15k),
color = "black") +
scale_fill_gradient(
low = "white",
high = "navy") +
theme_void() +
coord_map("polyconic") +
labs(fill = "States with Counties with PHS rates higher than 15k") +
theme(legend.position = "bottom")

#EXAMPLE
library(maps)
library(usdata)
state_borders <- map_data("state") %>% 
mutate(state = state2abbr(region)) %>% 
select(-subregion)
head(state_borders)

#gives an avg and filters ou territories, groups by state from melted data
state_prevent_all = ndimdf_preventable1 %>%
filter(!is.na(value), !state  %in% "US")  %>% 
group_by(state) %>% 
summarize(avg_phs_rate = mean(value)) 
 #takes the abbreviations in state and spells it out in a new column called "State)
  
  
state_prevent_plot <- state_borders %>%
left_join(state_prevent_all,
by = join_by(state == state ))#state_borders) #joins on common key in df1 and df2 

state_prevent_plot %>%
ggplot() +
geom_polygon(aes(x = long, y = lat,
group = group ,
fill = avg_phs_rate),
color = "black") +
scale_fill_gradient(
low = "white",
high = "navy") +
theme_void() +
coord_map("polyconic") +
labs(fill = "Avg PHS Rate") +
theme(legend.position = "bottom")

```


```{r}
library(ggcorrplot)
correlate3 = data_long %>% 
  dplyr::select(state,v005_rawvalue, v023_rawvalue, v044_rawvalue, v168_rawvalue )

cor_matrix = cor(correlate3)
ggcorrplot(cor_matrix)
  
  
```

```{r}
# plotting a bar graph 
#create new df that includes the primary care ratio, # of PCP, population; do the same with other primary care providers; mammographhy screening and flu vaccination(includes race data)

#v004 = prrimary care physicians 
#v004_other=   ratio of population to PCP
#v050 mammography screening
#131 = other primary care physicians
# 155 flu vaccination 
access_care = data[, c("state", "county","v005_rawvalue","v005_numerator", "v005_denominator","v005_race_aian", "v005_race_asian","v005_race_black", "v005_race_white", "v005_race_hispanic", "v004_rawvalue", "v004_other_data_1" , "v131_rawvalue" , "v131_other_data_1", "v050_rawvalue", "v050_numerator", "v050_denominator", "v050_race_aian", "v050_race_asian", "v050_race_black", "v050_race_white", "v050_race_hispanic",  "v155_rawvalue", "v155_numerator", "v155_denominator", "v155_race_aian", "v155_race_asian", "v155_race_black", "v155_race_white", "v155_race_hispanic"  )]

flu = access_care %>% select(1,2,3, 6:10, 23, 26:30)
melt_flu = melt(flu, id = c("state", "county", "v005_rawvalue", "v155_rawvalue"),variable.name='race')
mammogram = access_care %>%  select(1,2,3, 6:10, 15, 18:22)
melt_mammography = melt(mammogram, id = c("state", "county", "v005_rawvalue", "v050_rawvalue"),variable.name='race' )

```





```{r}
# scatterplot of flu

flu_scatter <- ggplot(melt_flu, aes(x = v155_rawvalue, y = v005_rawvalue, color = race)) +
  geom_point(alpha = 0.2) +
  labs(x = descriptions[["v155_rawvalue/Flu Vax Rate"]], y = "Preventable Hospital Stays") +
  scale_color_discrete(labels = c("AIAN", "Asian", "Black", "White", "Hispanic")) +
  theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    axis.title = element_text(color = "white"),
    axis.text = element_text(color = "white"),
    legend.background = element_rect(fill = "black"),
    legend.text = element_text(color = "white")
  ) +
  geom_smooth()

  print(flu_scatter)
  
#individual
  
ggplot(flu, aes(x = v155_race_aian, y = v005_race_aian )) + geom_point(alpha = 0.8, color = "orange") + ggtitle("flu vax rates vs preventable stays for aian") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)
ggplot(flu, aes(x = v155_race_asian, y = v005_race_asian )) + geom_point(alpha = 0.8, color = "blue") + ggtitle("flu vax rates vs preventable stays for asian") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)
ggplot(flu, aes(x = v155_race_black, y = v005_race_black )) + geom_point(alpha = 0.8, color = "green") + ggtitle("flu vax rates vs preventable stays for black") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)
ggplot(flu, aes(x = v155_race_white, y = v005_race_white )) + geom_point(alpha = 0.8, color = "pink") + ggtitle("flu vax rates vs preventable stays for white") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)
ggplot(flu, aes(x = v155_race_hispanic, y = v005_race_hispanic )) + geom_point(alpha = 0.8, color = "red") + ggtitle("flu vax rates vs preventable stays for hispanic") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)
```
```{r}
mammogram_scatter <- ggplot(melt_mammography, aes(x = v050_rawvalue, y = v005_rawvalue, color = race)) +
  geom_point(alpha = 0.2) +
  labs(x = descriptions[["v050_rawvalue/Mammogram Screening Rate"]], y = "Preventable Hospital Stays") +
  scale_color_discrete(labels = c("AIAN", "Asian", "Black", "White", "Hispanic")) +
  theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    axis.title = element_text(color = "white"),
    axis.text = element_text(color = "white"),
    legend.background = element_rect(fill = "black"),
    legend.text = element_text(color = "white")
  ) +
  geom_smooth()

  print(mammogram_scatter)
  
#individual
  
ggplot(mammogram, aes(x = v050_race_aian, y = v005_race_aian )) + geom_point(alpha = 0.8, color = "orange") + ggtitle("mammogram rates vs preventable stays for aian") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)

ggplot(mammogram, aes(x = v050_race_asian, y = v005_race_asian )) + geom_point(alpha = 0.8, color = "blue") + ggtitle("mammogram rates vs preventable stays for asian") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)
ggplot(mammogram, aes(x = v050_race_black, y = v005_race_black )) + geom_point(alpha = 0.8, color = "green") + ggtitle("mammogram rates vs preventable stays for black") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)

ggplot(mammogram, aes(x = v050_race_white, y = v005_race_white )) + geom_point(alpha = 0.8, color = "pink") + ggtitle("mammogram rates vs preventable stays for white") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)
ggplot(mammogram, aes(x = v050_race_hispanic, y = v005_race_hispanic )) + geom_point(alpha = 0.8, color = "red") + ggtitle("mammogram ratesvs preventable stays for hispanic") +geom_smooth() + xlim(0, 0.8) + ylim(0, 30000)
```

```{r}

#chloropleth for flu
flu_chloro = melt_flu %>%
filter(!is.na(value), !state  %in% "US")  %>% 
group_by(state) %>% 
summarize(avg_flu_vax_rate = mean(v155_rawvalue)) 
 #takes the abbreviations in state and spells it out in a new column called "State)
  
  
flu_chloro_plot <- state_borders %>%
left_join(flu_chloro,
by = join_by(state == state ))#state_borders) #joins on common key in df1 and df2 

flu_chloro_plot %>%
ggplot() +
geom_polygon(aes(x = long, y = lat,
group = group ,
fill = avg_flu_vax_rate),
color = "black") +
scale_fill_gradient(
low = "white",
high = "navy") +
theme_void() +
coord_map("polyconic") +
labs(fill = "Avg Flu Vax Rate") +
theme(legend.position = "bottom")


#chloropleth for mammograms
mam_chloro = melt_mammography %>%
filter(!is.na(value), !state  %in% "US")  %>% 
group_by(state) %>% 
summarize(avg_mam_rate = mean(v050_rawvalue)) 
 #takes the abbreviations in state and spells it out in a new column called "State)
  
  
mam_chloro_plot <- state_borders %>%
left_join(mam_chloro,
by = join_by(state == state ))#state_borders) #joins on common key in df1 and df2 

mam_chloro_plot %>%
ggplot() +
geom_polygon(aes(x = long, y = lat,
group = group ,
fill = avg_mam_rate),
color = "black") +
scale_fill_gradient(
low = "white",
high = "navy") +
theme_void() +
coord_map("polyconic") +
labs(fill = "Avg Mammorgraphy Rate") +
theme(legend.position = "bottom")
```

```{r}
#chloropleth for PCP
pcp_chloro = access_care %>%
filter(!is.na(v004_other_data_1), !state  %in% "US")  %>% 
group_by(state) %>% 
summarize(avg_pcp_ratio = mean(v004_other_data_1)) 
 #takes the abbreviations in state and spells it out in a new column called "State)
  
  
pcp_chloro_plot <- state_borders %>%
left_join(pcp_chloro,
by = join_by(state == state ))#state_borders) #joins on common key in df1 and df2 

pcp_chloro_plot %>%
ggplot() +
geom_polygon(aes(x = long, y = lat,
group = group ,
fill = avg_pcp_ratio),
color = "black") +
scale_fill_gradient(
low = "white",
high = "navy") +
theme_void() +
coord_map("polyconic") +
labs(fill = "Avg PCP Ratio by State") +
theme(legend.position = "bottom")

#chloropleth for other PCP
pcp_chloro1 = access_care %>%
filter(!is.na(v131_other_data_1), !state  %in% "US")  %>% 
group_by(state) %>% 
summarize(avg_other_pcp_ratio = mean(v131_other_data_1)) 
 #takes the abbreviations in state and spells it out in a new column called "State)
  
  
pcp_chloro_plot1 <- state_borders %>%
left_join(pcp_chloro1,
by = join_by(state == state ))#state_borders) #joins on common key in df1 and df2 

pcp_chloro_plot1 %>%
ggplot() +
geom_polygon(aes(x = long, y = lat,
group = group ,
fill = avg_other_pcp_ratio),
color = "black") +
scale_fill_gradient(
low = "white",
high = "navy") +
theme_void() +
coord_map("polyconic") +
labs(fill = "Avg Other PCP Ratio by State") +
theme(legend.position = "bottom")
```
```{r}
#plotting PCP against the PHS via race

#PCP AIAIN

ggplot(access_care, aes( x = v004_other_data_1, y = v005_race_aian)) + geom_point(alpha = 0.8, color = "blue") + ggtitle("Ratio of PCP to Population vs PHS for AIAN")
#PCP ASIAN
ggplot(access_care, aes( x = v004_other_data_1, y = v005_race_asian)) + geom_point(alpha = 0.8, color = "blue") + ggtitle("Ratio of PCP to Population vs PHS for ASIAN")
#PCP BLACK
ggplot(access_care, aes( x = v004_other_data_1, y = v005_race_black)) + geom_point(alpha = 0.8, color = "blue") + ggtitle("Ratio of PCP to Population vs PHS for BLACK")
#PCP WHITE 
ggplot(access_care, aes( x = v004_other_data_1, y = v005_race_white)) + geom_point(alpha = 0.8, color = "blue") + ggtitle("Ratio of PCP to Population vs PHS for WHITE")
#PCP HISPANIC
ggplot(access_care, aes( x = v004_other_data_1, y = v005_race_hispanic)) + geom_point(alpha = 0.8, color = "blue") + ggtitle("Ratio of PCP to Population vs PHS for HISPANIC")


races = c("aian", "asian", "black", "white", "hispanic")

for (subgroup in races) {
  plot <- ggplot(access_care, aes(x = v004_other_data_1, y = get(paste0("v005_race_", subgroup)))) +
    geom_point(alpha = 0.8, color = "blue") +
    ggtitle(paste("Ratio of PCP to population vs PHS for", subgroup))
  print(plot)
}


```

